using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public struct StructLanguage {
    public string ch;
    public string en;
}
public static class ConfLanguage {

    public static readonly Dictionary<string, StructLanguage> config = new Dictionary<string, StructLanguage>() {
        ["simplified Chinese"] = new StructLanguage() { ch = "简体中文", en = "Simplified Chinese" },
        ["English"] = new StructLanguage() { ch = "英文", en = "English" },
        ["Race"] = new StructLanguage() { ch = "种族", en = "Race" },
        ["StartGame"] = new StructLanguage() { ch = "开始游戏", en = "StartGame" },
        ["Race"] = new StructLanguage() { ch = "种族", en = "Race" },
        ["Dress"] = new StructLanguage() { ch = "装扮", en = "Dress" },
        ["Body"] = new StructLanguage() { ch = "身体", en = "Body" },
        ["Face"] = new StructLanguage() { ch = "脸部", en = "Face" },
        ["Sleek"] = new StructLanguage() { ch = "光滑", en = "Sleek" },
        ["HumanFemale"] = new StructLanguage() { ch = "人类女性", en = "Human Female" },
        ["HumanMale"] = new StructLanguage() { ch = "人类男性", en = "Human Male" },
        ["Elf Female"] = new StructLanguage() { ch = "精灵女性", en = "Elf Female" },
        ["Elf Male"] = new StructLanguage() { ch = "精灵男性", en = "Elf Male" },
        ["Hair"] = new StructLanguage() { ch = "头发", en = "Hair" },
        ["Buzzcut"] = new StructLanguage() { ch = "寸头", en = "Buzzcut" },
        ["Military Cut"] = new StructLanguage() { ch = "时髦", en = "Military Cut" },
        ["HairX"] = new StructLanguage() { ch = "后梳", en = "HairX" },
        ["MaleShortHair"] = new StructLanguage() { ch = "短发", en = "MaleShortHair" },
        ["The Rebel"] = new StructLanguage() { ch = "光头", en = "The Rebel" },
        ["The Pompadour"] = new StructLanguage() { ch = "长发", en = "The Pompadour" },
        ["The Middle-Ager"] = new StructLanguage() { ch = "地中海", en = "The Middle-Ager" },
        ["Feet"] = new StructLanguage() { ch = "脚", en = "Feet" },
        ["Tall Shoes Black"] = new StructLanguage() { ch = "黑色", en = "Tall Shoes Black" },
        ["Tall Shoes"] = new StructLanguage() { ch = "白色", en = "Tall Shoes" },
        ["Mystic Robe Shoes"] = new StructLanguage() { ch = "布鞋", en = "Mystic Robe Shoes" },
        ["MaleChallengerBoots"] = new StructLanguage() { ch = "长靴", en = "MaleChallengerBoots" },
        ["Complexion"] = new StructLanguage() { ch = "局面", en = "Complexion" },
        ["Smooth"] = new StructLanguage() { ch = "光滑的", en = "Smooth" },
        ["Chest"] = new StructLanguage() { ch = "上身", en = "Chest" },
        ["chest"] = new StructLanguage() { ch = "胸部", en = "Chest" },
        ["MaleHoodie"] = new StructLanguage() { ch = "男帽衫", en = "MaleHoodie" },
        ["Mystic Robe"] = new StructLanguage() { ch = "神秘长袍", en = "Mystic Robe" },
        ["Shirt 1"] = new StructLanguage() { ch = "衬衫1", en = "Shirt 1" },
        ["Shirt 2"] = new StructLanguage() { ch = "衬衫2", en = "Shirt 2" },
        ["Shirt 3"] = new StructLanguage() { ch = "衬衫3", en = "Shirt 3" },
        ["Shirt 4"] = new StructLanguage() { ch = "衬衫4", en = "Shirt 4" },
        ["trunk"] = new StructLanguage() { ch = "躯干", en = "trunk" },
        ["MaleChallengerTorso"] = new StructLanguage() { ch = "挑战者", en = "MaleChallengerTorso" },
        ["ClothRobeRecipe"] = new StructLanguage() { ch = "布袍", en = "ClothRobeRecipe" },
        ["Legs"] = new StructLanguage() { ch = "下身", en = "Legs" },
        ["MaleSweatPants"] = new StructLanguage() { ch = "运动裤", en = "Sweat Pants" },
        ["Old Jeans"] = new StructLanguage() { ch = "旧牛仔裤", en = "Old Jeans" },
        ["Jeans"] = new StructLanguage() { ch = "牛仔裤", en = "Jeans" },
        ["WrappedPants"] = new StructLanguage() { ch = "裹身裤", en = "WrappedPants" },
        ["Shorts"] = new StructLanguage() { ch = "短裤", en = "Shorts" },
        ["Irresistable Underwear"] = new StructLanguage() { ch = "花短裤", en = "Irresistable Underwear" },
        ["MakeMeFatJeans"] = new StructLanguage() { ch = "牛仔裤", en = "MakeMeFatJeans" },
        ["Hands"] = new StructLanguage() { ch = "手", en = "Hands" },
        ["Hands high quality"] = new StructLanguage() { ch = "高质量的手", en = "Hands high quality" },
        ["Gloves of Hammer"] = new StructLanguage() { ch = "锤子手套", en = "Gloves of Hammer" },
        ["MaleChallengerGloves"] = new StructLanguage() { ch = "男性挑战者手套", en = "MaleChallengerGloves" },
        ["AlternateHead"] = new StructLanguage() { ch = "候补负责人", en = "AlternateHead" },
        ["Low Poly Head"] = new StructLanguage() { ch = "低聚头", en = "Low Poly Head" },
        ["Head"] = new StructLanguage() { ch = "头", en = "Head" },
        ["head"] = new StructLanguage() { ch = "头部", en = "Head" },
        ["Beard"] = new StructLanguage() { ch = "胡须", en = "Beard" },
        ["Devilish Goatee"] = new StructLanguage() { ch = "口子胡", en = "Devilish Goatee" },
        ["Bums Beard"] = new StructLanguage() { ch = "络腮胡", en = "Bums Beard" },
        ["Manly Beard"] = new StructLanguage() { ch = "浓密络腮胡", en = "Manly Beard" },
        ["Eyebrows"] = new StructLanguage() { ch = "眉毛", en = "Eyebrows" },
        ["Brow 1"] = new StructLanguage() { ch = "浏览器1", en = "Brow 1" },
        ["Brow 2"] = new StructLanguage() { ch = "浏览器2", en = "Brow 2" },
        ["High-Res Brows"] = new StructLanguage() { ch = "高分辨率眉毛", en = "High-Res Brows" },
        ["High-Res Brows 2"] = new StructLanguage() { ch = "高分辨率眉毛2", en = "High-Res Brows 2" },
        ["Eyes"] = new StructLanguage() { ch = "眼睛", en = "Eyes" },
        ["Alligator Eyes"] = new StructLanguage() { ch = "鳄鱼眼睛", en = "Alligator Eyes" },
        ["Alligator Eyes Alt Test"] = new StructLanguage() { ch = "鳄鱼眼睛替代测试", en = "Alligator Eyes Alt Test" },
        ["Cat Eyes"] = new StructLanguage() { ch = "猫眼", en = "Cat Eyes" },
        ["Cat Eyes Alt"] = new StructLanguage() { ch = "猫眼Alt", en = "Cat Eyes Alt" },
        ["large Eyes"] = new StructLanguage() { ch = "大眼睛", en = "large Eyes" },
        ["Old Face"] = new StructLanguage() { ch = "老面孔", en = "Old Face" },
        ["TrollFace"] = new StructLanguage() { ch = "巨魔脸", en = "TrollFace" },
        ["AlienHeadMorph"] = new StructLanguage() { ch = "异形头变形", en = "AlienHeadMorph" },
        ["Helmet"] = new StructLanguage() { ch = "头盔", en = "Helmet" },
        ["Mystic Robe Hood"] = new StructLanguage() { ch = "神秘长袍帽", en = "Mystic Robe Hood" },
        ["Underwear"] = new StructLanguage() { ch = "内衣", en = "Underwear" },
        ["Default Underwear"] = new StructLanguage() { ch = "默认内衣", en = "Default Underwear" },
        ["Ears"] = new StructLanguage() { ch = "耳朵", en = "Ears" },
        ["BlendShapeRecipe"] = new StructLanguage() { ch = "混合形状配方", en = "BlendShapeRecipe" },
        ["ElfEarsMorph"] = new StructLanguage() { ch = "精灵耳朵变形", en = "ElfEarsMorph" },
        ["Physique"] = new StructLanguage() { ch = "体形", en = "Physique" },
        ["OverweightMale"] = new StructLanguage() { ch = "超重男性", en = "OverweightMale" },
        ["Shoulders"] = new StructLanguage() { ch = "肩膀", en = "Shoulders" },
        ["MaleChallengerShouderPads"] = new StructLanguage() { ch = "男性挑战者手垫", en = "MaleChallengerShouderPads" },
        ["Skin"] = new StructLanguage() { ch = "皮肤", en = "Skin" },
        ["Hair"] = new StructLanguage() { ch = "头发", en = "Hair" },
        ["Eyes"] = new StructLanguage() { ch = "眼睛", en = "Eyes" },
        ["Pants"] = new StructLanguage() { ch = "裤子", en = "Pants" },
        ["skinGreenness"] = new StructLanguage() { ch = "皮肤绿色", en = "skinGreenness" },
        ["skinBlueness"] = new StructLanguage() { ch = "皮肤发青", en = "skinBlueness" },
        ["skinRedness"] = new StructLanguage() { ch = "皮肤发红", en = "skinRedness" },
        ["breastCleavage"] = new StructLanguage() { ch = "乳沟", en = "breastCleavage" },
        ["height"] = new StructLanguage() { ch = "高度", en = "height" },
        ["headSize"] = new StructLanguage() { ch = "头部尺寸", en = "headSize" },
        ["headWidth"] = new StructLanguage() { ch = "头部宽度", en = "headWidth" },
        ["neckThickness"] = new StructLanguage() { ch = "颈部厚度", en = "neckThickness" },
        ["armLength"] = new StructLanguage() { ch = "臂长", en = "armLength" },
        ["forearmLength"] = new StructLanguage() { ch = "前臂长度", en = "forearmLength" },
        ["armWidth"] = new StructLanguage() { ch = "臂宽", en = "armWidth" },
        ["forearmWidth"] = new StructLanguage() { ch = "前臂宽度", en = "forearmWidth" },
        ["handsSize"] = new StructLanguage() { ch = "手的大小", en = "handsSize" },
        ["feetSize"] = new StructLanguage() { ch = "脚大小", en = "feetSize" },
        ["legSeparation"] = new StructLanguage() { ch = "腿部间距", en = "legSeparation" },
        ["upperMuscle"] = new StructLanguage() { ch = "上部肌肉", en = "upperMuscle" },
        ["lowerMuscle"] = new StructLanguage() { ch = "下肌肉", en = "lowerMuscle" },
        ["upperWeight"] = new StructLanguage() { ch = "上部重量", en = "upperWeight" },
        ["lowerWeight"] = new StructLanguage() { ch = "重量", en = "lowerWeight" },
        ["legsSize"] = new StructLanguage() { ch = "腿部尺寸", en = "legsSize" },
        ["belly"] = new StructLanguage() { ch = "腹部", en = "belly" },
        ["waist"] = new StructLanguage() { ch = "腰", en = "waist" },
        ["gluteusSize"] = new StructLanguage() { ch = "臀肌大小", en = "gluteusSize" },
        ["earsSize"] = new StructLanguage() { ch = "耳朵大小", en = "earsSize" },
        ["earsPosition"] = new StructLanguage() { ch = "耳朵的位置", en = "earsPosition" },
        ["earsRotation"] = new StructLanguage() { ch = "耳朵旋转", en = "earsRotation" },
        ["noseSize"] = new StructLanguage() { ch = "鼻子大小", en = "noseSize" },
        ["noseCurve"] = new StructLanguage() { ch = "鼻子曲线", en = "noseCurve" },
        ["noseWidth"] = new StructLanguage() { ch = "鼻头宽度", en = "noseWidth" },
        ["noseInclination"] = new StructLanguage() { ch = "鼻子倾斜", en = "noseInclination" },
        ["nosePosition"] = new StructLanguage() { ch = "鼻头位置", en = "nosePosition" },
        ["nose"] = new StructLanguage() { ch = "鼻子", en = "nose" },
        ["nosePronounced"] = new StructLanguage() { ch = "突出鼻子", en = "nosePronounced" },
        ["noseFlatten"] = new StructLanguage() { ch = "压平鼻子", en = "noseFlatten" },
        ["chin"] = new StructLanguage() { ch = "下巴", en = "chin" },
        ["chinSize"] = new StructLanguage() { ch = "下巴尺寸", en = "chinSize" },
        ["chinPronounced"] = new StructLanguage() { ch = "下巴大小", en = "chinPronounced" },
        ["chinPosition"] = new StructLanguage() { ch = "下巴位置", en = "chinPosition" },
        ["mandibleSize"] = new StructLanguage() { ch = "下颌骨大小", en = "mandibleSize" },
        ["jawsSize"] = new StructLanguage() { ch = "颌骨大小", en = "jawsSize" },
        ["jawsPosition"] = new StructLanguage() { ch = "颌骨位置", en = "jawsPosition" },
        ["cheekSize"] = new StructLanguage() { ch = "脸颊大小", en = "cheekSize" },
        ["cheekPosition"] = new StructLanguage() { ch = "脸颊位置", en = "cheekPosition" },
        ["lowCheekPronounced"] = new StructLanguage() { ch = "低脸颊大小", en = "lowCheekPronounced" },
        ["lowCheekPosition"] = new StructLanguage() { ch = "低脸颊位置", en = "lowCheekPosition" },
        ["foreheadSize"] = new StructLanguage() { ch = "前额大小", en = "foreheadSize" },
        ["foreheadPosition"] = new StructLanguage() { ch = "前额位置", en = "foreheadPosition" },
        ["lipsSize"] = new StructLanguage() { ch = "嘴唇大小", en = "lipsSize" },
        ["mouth"] = new StructLanguage() { ch = "嘴巴", en = "mouth" },
        ["mouthSize"] = new StructLanguage() { ch = "嘴巴大小", en = "mouthSize" },
        ["eyeRotation"] = new StructLanguage() { ch = "眼睛旋转", en = "eyeRotation" },
        ["eyeSize"] = new StructLanguage() { ch = "眼睛大小", en = "eyeSize" },
        ["breastSize"] = new StructLanguage() { ch = "乳房大小", en = "breastSize" },
        ["eyeSpacing"] = new StructLanguage() { ch = "眼间距", en = "eyeSpacing" },
        ["Undies"] = new StructLanguage() { ch = "内衣", en = "Undies" },
        ["Ladies Intimate Wear"] = new StructLanguage() { ch = "内衣2", en = "Ladies Intimate Wear" },
        ["FemaleHandsMid"] = new StructLanguage() { ch = "女性双手中间", en = "Female Hands Mid" },
        ["FemaleTankTop"] = new StructLanguage() { ch = "背心", en = "Female Tank Top" },
        ["FemaleSportPants"] = new StructLanguage() { ch = "高腰裤", en = "Female Sport Pants" },
        ["Pants 1"] = new StructLanguage() { ch = "低腰裤", en = "Pants 1" },
        ["Pants 2"] = new StructLanguage() { ch = "花裤子", en = "Pants 2" },
        ["FemaleLongHair"] = new StructLanguage() { ch = "中分", en = "Long Hair" },
        ["FemalePonyTail"] = new StructLanguage() { ch = "马尾1", en = "Pony Tail" },
        ["Hair 1"] = new StructLanguage() { ch = "双马尾", en = "Hair 1" },
        ["Hair 2"] = new StructLanguage() { ch = "短发", en = "Hair 2" },
        ["Hair 3"] = new StructLanguage() { ch = "梨花头", en = "Hair 3" },
        ["BoneyTail"] = new StructLanguage() { ch = "马尾2", en = "Boney Tail" },
        ["High Tops - Black"] = new StructLanguage() { ch = "黑色", en = "High Tops Black" },
        ["High Tops - Turquoise"] = new StructLanguage() { ch = "松绿", en = "High Tops Turquoise" },
        ["High Tops - White"] = new StructLanguage() { ch = "白色", en = "High Tops White" },
        ["Color"] = new StructLanguage() { ch = "颜色", en = "Color" },
        ["Lipstick"] = new StructLanguage() { ch = "口红", en = "Lipstick" },
        ["Shirt"] = new StructLanguage() { ch = "衬衫", en = "Shirt" },
        ["Pants Accent"] = new StructLanguage() { ch = "裤子", en = "Pants Accent" },
        ["Pants"] = new StructLanguage() { ch = "裤子", en = "Pants" },
    };
}
