using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public struct StructLanguage {
    public string ch;
    public string en;
}
public static class ConfLanguage {

    public static readonly Dictionary<string, StructLanguage> config = new Dictionary<string, StructLanguage>() {
        ["HumanFemale"] = new StructLanguage() { ch = "人类女", en = "Human Female" },
        ["HumanMale"] = new StructLanguage() { ch = "人类男", en = "Human Male" },
        ["Elf Female"] = new StructLanguage() { ch = "精灵女", en = "Elf Female" },
        ["Elf Male"] = new StructLanguage() { ch = "精灵男", en = "Elf Male" },
        ["Hair"] = new StructLanguage() { ch = "头发", en = "Hair" },
        ["Buzzcut"] = new StructLanguage() { ch = "Buzzcut", en = "Buzzcut" },
        ["Military Cut"] = new StructLanguage() { ch = "e军事削减", en = "Military Cut" },
        ["HairX"] = new StructLanguage() { ch = "HairX", en = "HairX" },
        ["MaleShortHair"] = new StructLanguage() { ch = "男性短发", en = "MaleShortHair" },
        ["The Rebel"] = new StructLanguage() { ch = "ee反叛者", en = "The Rebel" },
        ["The Pompadour"] = new StructLanguage() { ch = "ee蓬巴杜", en = "The Pompadour" },
        ["The Middle-Ager"] = new StructLanguage() { ch = "Th中年人", en = "The Middle-Ager" },
        ["Feet"] = new StructLanguage() { ch = "脚", en = "Feet" },
        ["Tall Shoes Black"] = new StructLanguage() { ch = "Ta黑色高帮鞋", en = "Tall Shoes Black" },
        ["Tall Shoes"] = new StructLanguage() { ch = "een高脚鞋", en = "Tall Shoes" },
        ["Mystic Robe Shoes"] = new StructLanguage() { ch = "Mys神秘长袍鞋", en = "Mystic Robe Shoes" },
        ["MaleChallengerBoots"] = new StructLanguage() { ch = "男性挑战者", en = "MaleChallengerBoots" },
        ["Complexion"] = new StructLanguage() { ch = "局面", en = "Complexion" },
        ["Smooth"] = new StructLanguage() { ch = "光滑的", en = "Smooth" },
        ["Chest"] = new StructLanguage() { ch = "胸部", en = "Chest" },
        ["MaleHoodie"] = new StructLanguage() { ch = "男帽衫", en = "MaleHoodie" },
        ["Mystic Robe"] = new StructLanguage() { ch = "e神秘长袍", en = "Mystic Robe" },
        ["Shirt 1"] = new StructLanguage() { ch = "e衬衫1", en = "Shirt 1" },
        ["Shirt 2"] = new StructLanguage() { ch = "e衬衫2", en = "Shirt 2" },
        ["Shirt 3"] = new StructLanguage() { ch = "e衬衫3", en = "Shirt 3" },
        ["MaleChallengerTorso"] = new StructLanguage() { ch = "男性挑战者", en = "MaleChallengerTorso" },
        ["ClothRobeRecipe"] = new StructLanguage() { ch = "ClothRobeRecipe", en = "ClothRobeRecipe" },
        ["Legs"] = new StructLanguage() { ch = "腿", en = "Legs" },
        ["MaleSweatPants"] = new StructLanguage() { ch = "男性运动裤", en = "MaleSweatPants" },
        ["Old Jeans"] = new StructLanguage() { ch = "ee旧牛仔裤", en = "Old Jeans" },
        ["Jeans"] = new StructLanguage() { ch = "牛仔裤", en = "Jeans" },
        ["WrappedPants"] = new StructLanguage() { ch = "包裹裤", en = "WrappedPants" },
        ["Shorts"] = new StructLanguage() { ch = "短裤", en = "Shorts" },
        ["Irresistable Underwear"] = new StructLanguage() { ch = "eIrre不可抗拒的内衣", en = "Irresistable Underwear" },
        ["MakeMeFatJeans"] = new StructLanguage() { ch = "MakeMeFatJeans", en = "MakeMeFatJeans" },
        ["Hands"] = new StructLanguage() { ch = "手", en = "Hands" },
        ["Hands high quality"] = new StructLanguage() { ch = "Ha高质量的手", en = "Hands high quality" },
        ["Gloves of Hammer"] = new StructLanguage() { ch = "G锤子手套", en = "Gloves of Hammer" },
        ["MaleChallengerGloves"] = new StructLanguage() { ch = "男性挑战者爱情", en = "MaleChallengerGloves" },
        ["AlternateHead"] = new StructLanguage() { ch = "替代广告", en = "AlternateHead" },
        ["Low Poly Head"] = new StructLanguage() { ch = "低聚头", en = "Low Poly Head" },
        ["Beard"] = new StructLanguage() { ch = "胡须", en = "Beard" },
        ["Devilish Goatee"] = new StructLanguage() { ch = "e魔鬼般的山羊胡", en = "Devilish Goatee" },
        ["Bums Beard"] = new StructLanguage() { ch = "een流浪汉胡子", en = "Bums Beard" },
        ["Manly Beard"] = new StructLanguage() { ch = "e男子汉的胡子", en = "Manly Beard" },
        ["Eyebrows"] = new StructLanguage() { ch = "眉毛", en = "Eyebrows" },
        ["Brow 1"] = new StructLanguage() { ch = "een浏览器1", en = "Brow 1" },
        ["Brow 2"] = new StructLanguage() { ch = "een浏览器2", en = "Brow 2" },
        ["High-Res Brows"] = new StructLanguage() { ch = "高分辨率眉毛", en = "High-Res Brows" },
        ["High-Res Brows 2"] = new StructLanguage() { ch = "R高分辨率眉毛2", en = "High-Res Brows 2" },
        ["Eyes"] = new StructLanguage() { ch = "眼睛", en = "Eyes" },
        ["Alligator Eyes"] = new StructLanguage() { ch = "eA鳄鱼眼睛", en = "Alligator Eyes" },
        ["Alligator Eyes Alt Test"] = new StructLanguage() { ch = "鳄鱼眼睛替代测试", en = "Alligator Eyes Alt Test" },
        ["Cat Eyes"] = new StructLanguage() { ch = "ee猫眼", en = "Cat Eyes" },
        ["Cat Eyes Alt"] = new StructLanguage() { ch = "猫眼Alt", en = "Cat Eyes Alt" },
        ["large Eyes"] = new StructLanguage() { ch = "e大眼睛", en = "large Eyes" },
        ["Face"] = new StructLanguage() { ch = "脸", en = "Face" },
        ["Old Face"] = new StructLanguage() { ch = "ee老面孔", en = "Old Face" },
        ["TrollFace"] = new StructLanguage() { ch = "巨魔脸", en = "TrollFace" },
        ["AlienHeadMorph"] = new StructLanguage() { ch = "AlienHeadMorph", en = "AlienHeadMorph" },
        ["Helmet"] = new StructLanguage() { ch = "头盔", en = "Helmet" },
        ["Mystic Robe Hood"] = new StructLanguage() { ch = "Mys神秘长袍帽", en = "Mystic Robe Hood" },
        ["Underwear"] = new StructLanguage() { ch = "内衣", en = "Underwear" },
        ["Default Underwear"] = new StructLanguage() { ch = "e默认内衣", en = "Default Underwear" },
        ["Ears"] = new StructLanguage() { ch = "耳朵", en = "Ears" },
        ["BlendShapeRecipe"] = new StructLanguage() { ch = "混合形状配方", en = "BlendShapeRecipe" },
        ["ElfEarsMorph"] = new StructLanguage() { ch = "埃尔菲尔斯墨菲", en = "ElfEarsMorph" },
        ["Physique"] = new StructLanguage() { ch = "体形", en = "Physique" },
        ["OverweightMale"] = new StructLanguage() { ch = "超重男性", en = "OverweightMale" },
        ["Shoulders"] = new StructLanguage() { ch = "肩膀", en = "Shoulders" },
        ["MaleChallengerShouderPads"] = new StructLanguage() { ch = "男性挑战者", en = "MaleChallengerShouderPads" },
        ["Skin"] = new StructLanguage() { ch = "皮肤", en = "Skin" },
        ["Hair"] = new StructLanguage() { ch = "头发", en = "Hair" },
        ["Eyes"] = new StructLanguage() { ch = "眼睛", en = "Eyes" },
        ["Pants"] = new StructLanguage() { ch = "裤子", en = "Pants" },
        ["skinGreenness"] = new StructLanguage() { ch = "皮肤绿色", en = "skinGreenness" },
        ["skinBlueness"] = new StructLanguage() { ch = "皮肤发青", en = "skinBlueness" },
        ["skinRedness"] = new StructLanguage() { ch = "皮肤发红", en = "skinRedness" },
        ["height"] = new StructLanguage() { ch = "高度", en = "height" },
        ["headSize"] = new StructLanguage() { ch = "头部尺寸", en = "headSize" },
        ["headWidth"] = new StructLanguage() { ch = "标题", en = "headWidth" },
        ["neckThickness"] = new StructLanguage() { ch = "颈部厚度", en = "neckThickness" },
        ["armLength"] = new StructLanguage() { ch = "臂长", en = "armLength" },
        ["forearmLength"] = new StructLanguage() { ch = "前臂长度", en = "forearmLength" },
        ["armWidth"] = new StructLanguage() { ch = "臂宽", en = "armWidth" },
        ["forearmWidth"] = new StructLanguage() { ch = "前臂宽度", en = "forearmWidth" },
        ["handsSize"] = new StructLanguage() { ch = "手型尺寸", en = "handsSize" },
        ["feetSize"] = new StructLanguage() { ch = "feetSize", en = "feetSize" },
        ["legSeparation"] = new StructLanguage() { ch = "腿部分离", en = "legSeparation" },
        ["upperMuscle"] = new StructLanguage() { ch = "高级肌肉", en = "upperMuscle" },
        ["lowerMuscle"] = new StructLanguage() { ch = "lowerMuscle", en = "lowerMuscle" },
        ["upperWeight"] = new StructLanguage() { ch = "上八", en = "upperWeight" },
        ["lowerWeight"] = new StructLanguage() { ch = "较低的重量", en = "lowerWeight" },
        ["legsSize"] = new StructLanguage() { ch = "legsSize", en = "legsSize" },
        ["belly"] = new StructLanguage() { ch = "腹部", en = "belly" },
        ["waist"] = new StructLanguage() { ch = "腰", en = "waist" },
        ["gluteusSize"] = new StructLanguage() { ch = "讨论", en = "gluteusSize" },
        ["earsSize"] = new StructLanguage() { ch = "earsSize", en = "earsSize" },
        ["earsPosition"] = new StructLanguage() { ch = "earsPosition", en = "earsPosition" },
        ["earsRotation"] = new StructLanguage() { ch = "旋转", en = "earsRotation" },
        ["noseSize"] = new StructLanguage() { ch = "noseSize", en = "noseSize" },
        ["noseCurve"] = new StructLanguage() { ch = "鼻曲线", en = "noseCurve" },
        ["noseWidth"] = new StructLanguage() { ch = "鼻宽", en = "noseWidth" },
        ["noseInclination"] = new StructLanguage() { ch = "鼻倾向", en = "noseInclination" },
        ["nosePosition"] = new StructLanguage() { ch = "机头位置", en = "nosePosition" },
        ["nosePronounced"] = new StructLanguage() { ch = "发音", en = "nosePronounced" },
        ["noseFlatten"] = new StructLanguage() { ch = "鼻翼扁平", en = "noseFlatten" },
        ["chinSize"] = new StructLanguage() { ch = "chinSize", en = "chinSize" },
        ["chinPronounced"] = new StructLanguage() { ch = "中文发音", en = "chinPronounced" },
        ["chinPosition"] = new StructLanguage() { ch = "中国位置", en = "chinPosition" },
        ["mandibleSize"] = new StructLanguage() { ch = "mandibleSize", en = "mandibleSize" },
        ["jawsSize"] = new StructLanguage() { ch = "jawsSize", en = "jawsSize" },
        ["jawsPosition"] = new StructLanguage() { ch = "jawsPosition", en = "jawsPosition" },
        ["cheekSize"] = new StructLanguage() { ch = "脸颊大小", en = "cheekSize" },
        ["cheekPosition"] = new StructLanguage() { ch = "脸颊位置", en = "cheekPosition" },
        ["lowCheekPronounced"] = new StructLanguage() { ch = "低脸颊发音", en = "lowCheekPronounced" },
        ["lowCheekPosition"] = new StructLanguage() { ch = "低脸颊位置", en = "lowCheekPosition" },
        ["foreheadSize"] = new StructLanguage() { ch = "额头尺寸", en = "foreheadSize" },
        ["foreheadPosition"] = new StructLanguage() { ch = "前额位置", en = "foreheadPosition" },
        ["lipsSize"] = new StructLanguage() { ch = "lipsSize", en = "lipsSize" },
        ["mouthSize"] = new StructLanguage() { ch = "口腔大小", en = "mouthSize" },
        ["eyeRotation"] = new StructLanguage() { ch = "眼睛旋转", en = "eyeRotation" },
        ["eyeSize"] = new StructLanguage() { ch = "眼睛大小", en = "eyeSize" },
        ["breastSize"] = new StructLanguage() { ch = "胸围", en = "breastSize" },
        ["eyeSpacing"] = new StructLanguage() { ch = "眼睛间距", en = "eyeSpacing" },
    };
}
