

local tbl ={
	[1] = 'EquipAttrR',
	[2] = 'Equip',
	[3] = 'Reward',
	[4] = 'Email',
	[5] = 'Result',
	[6] = 'GetEmailList',
	[7] = 'GetEmailListR',
	[8] = 'ReadEmail',
	[9] = 'ReadEmailR',
	[10] = 'GetEmailReward',
	[11] = 'GetEmailRewardR',
	[12] = 'DeleteEmail',
	[13] = 'DeleteEmailR',
	[14] = 'UpdateNewEmailR',
	[15] = 'DebugAddEmail',
	[16] = 'DebugAddEmailR',
	[17] = 'LoginGetEmailInfo',
	[18] = 'LoginGetEmailInfoR',
	[19] = 'CheckDelete',
	[20] = 'CheckDeleteR',
	LoginGetEmailInfo = 17,
	DeleteEmailR = 13,
	ReadEmailR = 9,
	GetEmailRewardR = 11,
	GetEmailListR = 7,
	ReadEmail = 8,
	EquipAttrR = 1,
	DeleteEmail = 12,
	UpdateNewEmailR = 14,
	Equip = 2,
	Result = 5,
	DebugAddEmail = 15,
	CheckDeleteR = 20,
	Email = 4,
	GetEmailList = 6,
	CheckDelete = 19,
	LoginGetEmailInfoR = 18,
	DebugAddEmailR = 16,
	GetEmailReward = 10,
	Reward = 3,
}

return tbl
