

local tbl ={
	[1] = 'Horse',
	[2] = 'HorseR',
	[3] = 'GetHorseInfo',
	[4] = 'GetHorseInfoR',
	[5] = 'ExpAdd',
	[6] = 'AddExpByItem',
	[7] = 'AddExpByItemR',
	[8] = 'SetHorseRiding',
	[9] = 'SetHorseRidingR',
	[10] = 'ChangeHorseView',
	[11] = 'ChangeHorseViewR',
	[12] = 'HorseSlotLevelUp',
	[13] = 'HorseSlotLevelUpR',
	[14] = 'FeedHorse',
	[15] = 'FeedHorseR',
	[16] = 'FeedHorseByMemory',
	[17] = 'FeedHorseByMemoryR',
	[18] = 'SaveItemToFeedMemory',
	[19] = 'SaveItemToFeedMemoryR',
	[20] = 'RmItemToFeedMemory',
	[21] = 'RmItemToFeedMemoryR',
	[22] = 'GetItemToFeedMemory',
	[23] = 'GetItemToFeedMemoryR',
	ChangeHorseViewR = 11,
	FeedHorseR = 15,
	FeedHorseByMemory = 16,
	HorseSlotLevelUpR = 13,
	FeedHorseByMemoryR = 17,
	SetHorseRidingR = 9,
	HorseR = 2,
	ExpAdd = 5,
	GetHorseInfoR = 4,
	AddExpByItemR = 7,
	FeedHorse = 14,
	ChangeHorseView = 10,
	HorseSlotLevelUp = 12,
	GetItemToFeedMemoryR = 23,
	RmItemToFeedMemoryR = 21,
	GetItemToFeedMemory = 22,
	GetHorseInfo = 3,
	RmItemToFeedMemory = 20,
	SaveItemToFeedMemory = 18,
	AddExpByItem = 6,
	Horse = 1,
	SaveItemToFeedMemoryR = 19,
	SetHorseRiding = 8,
}

return tbl
