local ret = {
	[1002] = {
		guide_id = 1002, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "makeBtn", --[[指引按钮]]
		next_guide = 1003, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		delay_time = 0.5, --[[任务延时(s)]]
		disc = "点这里，就可以进行打造了！", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 11, --[[大步骤]]
	} ,
	[1003] = {
		guide_id = 1003, --[[指引id]]
		ui_name = "equip", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "equipMode_2", --[[指引按钮]]
		next_guide = 1004, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		delay_time = 0.5, --[[任务延时(s)]]
		disc = "打造在这里~", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 11, --[[大步骤]]
	} ,
	[1004] = {
		guide_id = 1004, --[[指引id]]
		ui_name = "formula", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "img_right_left", --[[角色为1的指引按钮]]
		obj2_name = "img_right_left", --[[角色为2的指引按钮]]
		obj4_name = "img_right_left", --[[角色为4的指引按钮]]
		next_guide = 1005, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		delay_time = 0.5, --[[任务延时(s)]]
		disc = "打造之前需要选择一件装备~", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-80,150}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 1, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 11, --[[大步骤]]
	} ,
	[1005] = {
		guide_id = 1005, --[[指引id]]
		ui_name = "formula", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "formulaBtn", --[[指引按钮]]
		next_guide = 1006, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "试试打造吧~", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-30,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 11, --[[大步骤]]
	} ,
	[1006] = {
		guide_id = 1006, --[[指引id]]
		ui_name = "equip", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "equip_close", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "关闭打造界面！", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-85}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 11, --[[大步骤]]
	} ,
	[1008] = {
		guide_id = 1008, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "skill1", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击释放技能", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
	} ,
	[1009] = {
		guide_id = 1009, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "skill5", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击释放酷炫无双技", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
	} ,
	[1010] = {
		guide_id = 1010, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "makeBtn", --[[指引按钮]]
		next_guide = 1011, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "打开锻造界面", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1011] = {
		guide_id = 1011, --[[指引id]]
		ui_name = "equip", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "equipMode_1", --[[指引按钮]]
		next_guide = 1012, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "这里可以强化装备", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-20,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1012] = {
		guide_id = 1012, --[[指引id]]
		ui_name = "enhance", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "enhanceItem_20001", --[[指引按钮]]
		next_guide = 1013, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "选择一件装备", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {80,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1013] = {
		guide_id = 1013, --[[指引id]]
		ui_name = "enhance", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "qianghuaBtn", --[[指引按钮]]
		next_guide = 1014, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击强化按钮", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-40,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1014] = {
		guide_id = 1014, --[[指引id]]
		ui_name = "equip", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "equip_close", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "关闭界面", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-85}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1015] = {
		guide_id = 1015, --[[指引id]]
		ui_name = "pet_get", --[[UI名]]
		guide_type = 4, --[[指引类型]]
		obj_name = "close_click", --[[指引按钮]]
		next_guide = 1016, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "哇！获得了一个武将，快去看看吧！", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 3, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 4, --[[大步骤]]
	} ,
	[1016] = {
		guide_id = 1016, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "wujiangBtn", --[[指引按钮]]
		next_guide = 1019, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "点击这里查看武将", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-70,-130}, --[[微调位置]]
		guide_r = -45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 4, --[[大步骤]]
	} ,
	[1019] = {
		guide_id = 1019, --[[指引id]]
		ui_name = "hero_battle", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "goto_attack", --[[指引按钮]]
		next_guide = 1020, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击出战", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-20,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 4, --[[大步骤]]
	} ,
	[1020] = {
		guide_id = 1020, --[[指引id]]
		ui_name = "hero_common", --[[UI名]]
		guide_type = 2, --[[指引类型]]
		obj_name = "hero_close", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "关闭界面", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-85}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 4, --[[大步骤]]
	} ,
	[1021] = {
		guide_id = 1021, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "dailyActivityBtn", --[[指引按钮]]
		next_guide = 1022, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击日常按钮", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-125}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1022] = {
		guide_id = 1022, --[[指引id]]
		ui_name = "daily", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "yeqian", --[[角色为1的指引按钮]]
		obj2_name = "yeqian", --[[角色为2的指引按钮]]
		obj4_name = "yeqian", --[[角色为4的指引按钮]]
		next_guide = 1023, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "日常活动在这里都可以看到哦！", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-20,90}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 2, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1023] = {
		guide_id = 1023, --[[指引id]]
		ui_name = "daily", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "Scroll View", --[[角色为1的指引按钮]]
		obj2_name = "Scroll View", --[[角色为2的指引按钮]]
		obj4_name = "Scroll View", --[[角色为4的指引按钮]]
		next_guide = 1024, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "点击打开竞技界面", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 1, --[[按钮需要触发什么事件]]
		guide_tf = {20,-300}, --[[微调位置]]
		guide_r = -45, --[[指引角度z]]
		view_ty = 2, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1024] = {
		guide_id = 1024, --[[指引id]]
		ui_name = "pvp_common", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "page1", --[[角色为1的指引按钮]]
		obj2_name = "page1", --[[角色为2的指引按钮]]
		obj4_name = "page1", --[[角色为4的指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "来挑战一个对手吧！", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 2, --[[按钮需要触发什么事件]]
		guide_tf = {-200,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 1, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1025] = {
		guide_id = 1025, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "familyBtn", --[[指引按钮]]
		next_guide = 1026, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "赶快加入一个军团吧！", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1026] = {
		guide_id = 1026, --[[指引id]]
		ui_name = "legion_apply_list", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "Scroll View", --[[角色为1的指引按钮]]
		obj2_name = "Scroll View", --[[角色为2的指引按钮]]
		obj4_name = "Scroll View", --[[角色为4的指引按钮]]
		next_guide = 1027, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "可申请军团列表", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {240,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 2, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1027] = {
		guide_id = 1027, --[[指引id]]
		ui_name = "legion_apply_list", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "one_key_apply_btn", --[[指引按钮]]
		next_guide = 1028, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击按钮一键申请", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-50,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1028] = {
		guide_id = 1028, --[[指引id]]
		ui_name = "create_base_view", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "legion_apply_colse_btn", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "关闭界面", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-85}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1029] = {
		guide_id = 1029, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "mailBtn", --[[指引按钮]]
		next_guide = 1030, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击社交按钮可查看好友", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1030] = {
		guide_id = 1030, --[[指引id]]
		ui_name = "friend", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "friend_left", --[[角色为1的指引按钮]]
		obj2_name = "friend_left", --[[角色为2的指引按钮]]
		obj4_name = "friend_left", --[[角色为4的指引按钮]]
		next_guide = 1031, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "好友功能列表", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {30,120}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 2, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1031] = {
		guide_id = 1031, --[[指引id]]
		ui_name = "friend", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "friendPage2", --[[指引按钮]]
		next_guide = 1032, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "点击推荐好友", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {30,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1032] = {
		guide_id = 1032, --[[指引id]]
		ui_name = "recommend_friends", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "on_key_add_btn", --[[指引按钮]]
		next_guide = 1033, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "一键添加好友吧！", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-30,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1033] = {
		guide_id = 1033, --[[指引id]]
		ui_name = "social", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "closeSocialBtn", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "关闭界面", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-85}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
	} ,
	[1034] = {
		guide_id = 1034, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "dailyActivityBtn", --[[指引按钮]]
		next_guide = 1035, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击日常按钮", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-125}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
	} ,
	[1035] = {
		guide_id = 1035, --[[指引id]]
		ui_name = "daily", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "Scroll View", --[[角色为1的指引按钮]]
		obj2_name = "Scroll View", --[[角色为2的指引按钮]]
		obj4_name = "Scroll View", --[[角色为4的指引按钮]]
		next_guide = 1036, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "点击参与天机任务", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 3, --[[按钮需要触发什么事件]]
		guide_tf = {20,-300}, --[[微调位置]]
		guide_r = -45, --[[指引角度z]]
		view_ty = 2, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
	} ,
	[1036] = {
		guide_id = 1036, --[[指引id]]
		ui_name = "rotation_task", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "refresh_btn", --[[指引按钮]]
		next_guide = 1037, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击这里可以刷新任务", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-50,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
	} ,
	[1037] = {
		guide_id = 1037, --[[指引id]]
		ui_name = "rotation_task", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "get_task_btn", --[[指引按钮]]
		obj1_name = "Scroll View", --[[角色为1的指引按钮]]
		obj2_name = "Scroll View", --[[角色为2的指引按钮]]
		obj4_name = "Scroll View", --[[角色为4的指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "领取一个天机任务吧！", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-80,-300}, --[[微调位置]]
		guide_r = -45, --[[指引角度z]]
		view_ty = 2, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
	} ,
	[1038] = {
		guide_id = 1038, --[[指引id]]
		ui_name = "pet_get", --[[UI名]]
		guide_type = 4, --[[指引类型]]
		obj_name = "close_click", --[[指引按钮]]
		next_guide = 1039, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "获得了一个坐骑", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 3, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 5, --[[大步骤]]
	} ,
	[1039] = {
		guide_id = 1039, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 3, --[[指引类型]]
		obj_name = "mountBtn", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 3, --[[指引位置]]
		disc = "点击打开坐骑界面", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 5, --[[大步骤]]
	} ,
	[1043] = {
		guide_id = 1043, --[[指引id]]
		ui_name = "mainui_task_base", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "btn_fromto", --[[角色为1的指引按钮]]
		obj2_name = "btn_fromto", --[[角色为2的指引按钮]]
		obj4_name = "btn_fromto", --[[角色为4的指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "开启未知的旅途！", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 6, --[[按钮需要触发什么事件]]
		guide_tf = {-70,-50}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 1, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 2, --[[大步骤]]
	} ,
	[1044] = {
		guide_id = 1044, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "autoBtn", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击这里可以自动打怪", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 3, --[[大步骤]]
	} ,
	[1045] = {
		guide_id = 1045, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "appearanceBtn", --[[角色为1的指引按钮]]
		obj2_name = "appearanceBtn", --[[角色为2的指引按钮]]
		obj4_name = "appearanceBtn", --[[角色为4的指引按钮]]
		next_guide = 1046, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击外观按钮", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 4, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 6, --[[大步骤]]
	} ,
	[1046] = {
		guide_id = 1046, --[[指引id]]
		ui_name = "appearance", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "unlock_btn", --[[指引按钮]]
		next_guide = 1047, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击解锁外观", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-40,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 6, --[[大步骤]]
	} ,
	[1047] = {
		guide_id = 1047, --[[指引id]]
		ui_name = "appearance", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "close_btn", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "关闭界面", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-135}, --[[微调位置]]
		guide_r = 70, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 6, --[[大步骤]]
	} ,
	[1048] = {
		guide_id = 1048, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "makeBtn", --[[角色为1的指引按钮]]
		obj2_name = "makeBtn", --[[角色为2的指引按钮]]
		obj4_name = "makeBtn", --[[角色为4的指引按钮]]
		next_guide = 1049, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "打开锻造界面", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 5, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 8, --[[大步骤]]
	} ,
	[1049] = {
		guide_id = 1049, --[[指引id]]
		ui_name = "inlay_gem", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "equipGemItem_1", --[[指引按钮]]
		next_guide = 1050, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击镶嵌宝石孔", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 8, --[[大步骤]]
	} ,
	[1050] = {
		guide_id = 1050, --[[指引id]]
		ui_name = "gem_select", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "inlayBtn", --[[指引按钮]]
		next_guide = 1051, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击镶嵌", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 8, --[[大步骤]]
	} ,
	[1051] = {
		guide_id = 1051, --[[指引id]]
		ui_name = "equip_base", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "equip_close", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "关闭界面", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-85}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 1, --[[隐藏主界面攻击面板]]
		big_step = 8, --[[大步骤]]
	} ,
	[1052] = {
		guide_id = 1052, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "copyBtn", --[[角色为1的指引按钮]]
		obj2_name = "copyBtn", --[[角色为2的指引按钮]]
		obj4_name = "copyBtn", --[[角色为4的指引按钮]]
		next_guide = 1053, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击副本按钮", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 7, --[[按钮需要触发什么事件]]
		guide_tf = {40,-75}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
	} ,
	[1053] = {
		guide_id = 1053, --[[指引id]]
		ui_name = "tower", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "enter_btn", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击开启挑战按钮", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
	} ,
	[1054] = {
		guide_id = 1054, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "dailyActivityBtn", --[[指引按钮]]
		next_guide = 1055, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击日常按钮", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-125}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 7, --[[大步骤]]
	} ,
	[1055] = {
		guide_id = 1055, --[[指引id]]
		ui_name = "daily", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "yeqian", --[[角色为1的指引按钮]]
		obj2_name = "yeqian", --[[角色为2的指引按钮]]
		obj4_name = "yeqian", --[[角色为4的指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "点击参与每日任务", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 3, --[[按钮需要触发什么事件]]
		guide_tf = {-650,30}, --[[微调位置]]
		guide_r = -45, --[[指引角度z]]
		view_ty = 1, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 7, --[[大步骤]]
	} ,
	[1056] = {
		guide_id = 1056, --[[指引id]]
		ui_name = "zhujiemian", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "btn_background", --[[指引按钮]]
		obj1_name = "headBtn", --[[角色为1的指引按钮]]
		obj2_name = "headBtn", --[[角色为2的指引按钮]]
		obj4_name = "headBtn", --[[角色为4的指引按钮]]
		next_guide = 1057, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "点击人物头像", --[[指引描述]]
		add_button = 1, --[[是否加按钮]]
		butten_event = 8, --[[按钮需要触发什么事件]]
		guide_tf = {-30,-90}, --[[微调位置]]
		guide_r = -45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 9, --[[大步骤]]
	} ,
	[1057] = {
		guide_id = 1057, --[[指引id]]
		ui_name = "destiny_draw", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "btnOneKeyDraw", --[[指引按钮]]
		next_guide = 1058, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		delay_time = 1.0, --[[任务延时(s)]]
		disc = "点击一键猎命", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 9, --[[大步骤]]
	} ,
	[1058] = {
		guide_id = 1058, --[[指引id]]
		ui_name = "destiny_base", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "destinyType_1", --[[指引按钮]]
		next_guide = 1059, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "点击天命镶嵌", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {-30,-90}, --[[微调位置]]
		guide_r = -45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 9, --[[大步骤]]
	} ,
	[1059] = {
		guide_id = 1059, --[[指引id]]
		ui_name = "destiny_inlay", --[[UI名]]
		guide_type = 1, --[[指引类型]]
		obj_name = "add", --[[指引按钮]]
		obj1_name = "bodyItem_1", --[[角色为1的指引按钮]]
		obj2_name = "bodyItem_1", --[[角色为2的指引按钮]]
		obj4_name = "bodyItem_1", --[[角色为4的指引按钮]]
		next_guide = 1060, --[[下一个指引id(0=没有下一步)]]
		btn_place = 1, --[[指引位置]]
		disc = "点击镶嵌孔", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,23}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 9, --[[大步骤]]
	} ,
	[1060] = {
		guide_id = 1060, --[[指引id]]
		ui_name = "destiny_depot", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "btnSure", --[[指引按钮]]
		next_guide = 1061, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击确认", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {0,0}, --[[微调位置]]
		guide_r = 0, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 9, --[[大步骤]]
	} ,
	[1061] = {
		guide_id = 1061, --[[指引id]]
		ui_name = "player_base_ui", --[[UI名]]
		guide_type = 0, --[[指引类型]]
		obj_name = "playerCloseBtn", --[[指引按钮]]
		next_guide = 0, --[[下一个指引id(0=没有下一步)]]
		btn_place = 2, --[[指引位置]]
		disc = "点击关闭", --[[指引描述]]
		add_button = 0, --[[是否加按钮]]
		butten_event = 0, --[[按钮需要触发什么事件]]
		guide_tf = {20,-85}, --[[微调位置]]
		guide_r = 45, --[[指引角度z]]
		view_ty = 0, --[[视图类型]]
		show_atk_panel = 0, --[[隐藏主界面攻击面板]]
		big_step = 9, --[[大步骤]]
	} ,
}
return ret