
public enum AttrEnum {
    hp,
    sp,
    strength,
    magic,
    speed,
    defence,
    fireResistance,
    iceResistance,
    electricityResistance,
    poisonResistance,
    attackDistance,
    energy,
    weight,
    fireDamage,
    iceDamage,
    electricityDamage,
    poisonDamage,
    fireAppend,
    iceAppend,
    electricityAppend,
    poisonAppend,
    Combustion,
    Poisoning,
    Slow,
    bleeding,
    SunderArmor,
    Stealth,
    weightPlay,
    energyPlay,

}
